/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 真查库一次（SELECT 1）后返回；数据库不可用时由异常过滤器统一收口为失败包
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录
         * @description `account`（**手机号 或 登录账号名，二选一、服务端判别**）＋ 密码 → 双令牌 ＋ 当前人信息。失败一律 401 / 20002 且**不区分**「账号不存在」与「密码错」
         */
        post: operations["OrgController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新令牌
         * @description 用 `refresh_token` 换一对新令牌；**重新装载**最新角色与管辖部门（撤销经理后立即收窄数据范围）
         */
        post: operations["OrgController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前登录人
         * @description 返回角色 ＋ 管辖部门集合 ＋ 权限矩阵 ＋ 数据范围；`managed_dept_ids` 为空 = 非经理
         */
        get: operations["OrgController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 部门列表
         * @description 树形关系由 `parent_id` 自带，前端自行组树（含经理与关联产品线）
         */
        get: operations["OrgController_listDepartments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 员工列表
         * @description **不含密码哈希**；含主/兼部门、关联产品线、直属经理与角色码。**服务端按数据范围收敛**（管理员/总经理=全部；经理=管辖部门；销售=同部门，→ §4.2 G7）
         */
        get: operations["OrgController_listEmployees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 角色列表
         * @description 内置 6 条（`is_builtin`，内置不可删）
         */
        get: operations["OrgController_listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 权限矩阵
         * @description `perm_key × role_code → level` 全量矩阵行
         */
        get: operations["OrgController_listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 公司档案列表
         * @description 按 id 倒序（**分页 / 筛选属 M6 列表页**，本批给最近 100 条）。⚠ 接口 §5.4 列表项里的 `relation_count` / `old_customer` 属 C / E 域，跨域不许查表 ⇒ 待 M3/M4 提供
         */
        get: operations["CompanyController_listCompanies"];
        put?: never;
        /**
         * 建档公司
         * @description 服务端生成 `name_core`（供两段式查重第一段）。`credit_code` 撞码 → **409「请使用已有档案」**；**疑似重复不拦建档**（需求 §12.1 分支 4：保留「强行新建」出口）
         */
        post: operations["CompanyController_createCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/search-dup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 撞库查重
         * @description `phone` / `credit_code` 精确命中 → `same`；`name` 走两段式（`name_core` 前缀收缩 → 编辑距离判级 → `same` / `high_sim`）。**有候选即 `suggest=use_exists`**（疑似默认选现有），无候选才 `create_new`
         */
        post: operations["CompanyController_searchDup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 联系人列表
         * @description **列表出参一律 `phone_masked`**（→ §2.8，出参形态而非权限）
         */
        get: operations["CompanyController_listContacts"];
        put?: never;
        /**
         * 建档联系人
         * @description 主号先归一（去空格 / `+86` / `-`）再入库；**重复手机号 → 409**（软删后同号可再建）；命中历史号只提示 `phone_history_hint`、**不拦截**
         */
        post: operations["CompanyController_createContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 公司联系人
         * @description 含**历史就职 / 已离职标记**（`is_current`，→ B5）
         */
        get: operations["CompanyController_listCompanyContacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            /**
             * @description 服务可用
             * @example true
             */
            ok: boolean;
            /**
             * @description 数据库连通状态（真跑了一次 SELECT 1）
             * @example up
             */
            db: string;
        };
        LoginDto: {
            /**
             * @description 登录标识：**手机号 或 登录账号名**（二选一，服务端判别）；前端只有一个输入框
             * @example 13800000003
             */
            account: string;
            /**
             * @description 密码明文（仅本次请求内存，不入库、不进日志）
             * @example Dev@123456
             */
            password: string;
        };
        EntityRefDto: {
            /**
             * @description 主键（十进制字符串，防 JSON 精度丢失）
             * @example 1
             */
            id: string;
            /**
             * @description 名称
             * @example 华东销售一部
             */
            name: string;
        };
        UserVoDto: {
            /** @example 7 */
            id: string;
            /** @example 张三 */
            name: string;
            /**
             * @description 登录账号名（**可空**：为空则只能手机号登录；→ §5.2）。服务端**始终下发该键**，无值给 `null`
             * @example zhangsan
             */
            username: string | null;
            /**
             * @description 主角色码（一人多角色时取权限最大者；内置码见 A4）
             * @example sale
             */
            role: string;
            /** @description 主部门；无部门数据时为 null */
            dept: components["schemas"]["EntityRefDto"] | null;
            /**
             * @description 管辖部门集合；**空数组 = 非经理**
             * @example [
             *       "1",
             *       "2"
             *     ]
             */
            managed_dept_ids: string[];
            /**
             * @description 权限矩阵（perm_key → level），level ∈ visible / masked / denied
             * @example {
             *       "customer.view": "visible"
             *     }
             */
            permissions: {
                [key: string]: string;
            };
        };
        LoginResultDto: {
            /** @description 访问令牌（Bearer JWT，建议 2h） */
            access_token: string;
            /** @description 刷新令牌 */
            refresh_token: string;
            /** @description 当前登录人（前端据此渲染菜单 / 数据范围） */
            user: components["schemas"]["UserVoDto"];
        };
        RefreshDto: {
            /** @description 登录时下发的 `refresh_token`（JWT 串） */
            refresh_token: string;
        };
        RefreshResultDto: {
            /** @description 新的访问令牌 */
            access_token: string;
            /** @description 新的刷新令牌 */
            refresh_token: string;
        };
        DepartmentVoDto: {
            /** @example 1 */
            id: string;
            /** @example 华东分公司 */
            name: string;
            /**
             * @description 上级部门 id；`0` = 根（自引用不建外键）
             * @example 0
             */
            parent_id: string;
            /**
             * @description 客服开关
             * @example false
             */
            service_enabled: boolean;
            /**
             * @description 状态（active / disabled）
             * @example active
             */
            status: string;
            /** @description 部门经理集合（→ A3 `dept_manager`，多对多） */
            manager_ids: string[];
            /** @description 关联产品线集合（由 A7 的 `dept_ids` 反向索引而来） */
            product_line_ids: string[];
        };
        EmployeeVoDto: {
            /** @example 7 */
            id: string;
            /**
             * @description 工号
             * @example A007
             */
            work_no: string;
            /** @example 张三 */
            name: string;
            /**
             * @description 手机号（主入口唯一键）
             * @example 13800000000
             */
            phone: string;
            /**
             * @description 登录账号名（可空：为空则只能手机号登录）
             * @example zhangsan
             */
            username: string | null;
            /** @description 主部门 */
            primary_dept: components["schemas"]["EntityRefDto"] | null;
            /** @description 兼部门 */
            extra_depts: components["schemas"]["EntityRefDto"][];
            /** @description 关联产品线 */
            product_lines: components["schemas"]["EntityRefDto"][];
            /** @description 直属经理（审批链） */
            direct_manager: components["schemas"]["EntityRefDto"] | null;
            /**
             * @description 角色码集合（→ A5）
             * @example [
             *       "sale"
             *     ]
             */
            roles: string[];
            /**
             * @description 状态（active / resigned / disabled）
             * @example active
             */
            status: string;
        };
        RoleVoDto: {
            /**
             * @description 角色码（内置 6 条）
             * @example sale
             */
            code: string;
            /** @example 销售 */
            name: string;
            /**
             * @description 是否内置（内置不可删）
             * @example true
             */
            is_builtin: boolean;
        };
        PermissionVoDto: {
            /**
             * @description 权限键
             * @example customer.view
             */
            perm_key: string;
            /**
             * @description 角色码
             * @example sale
             */
            role_code: string;
            /**
             * @description 档位（visible / masked / denied）
             * @example visible
             */
            level: string;
        };
        CompanyVoDto: {
            /** @example 1 */
            id: string;
            /** @example 安徽鑫中网信息技术有限公司 */
            full_name: string;
            /**
             * @description 标准化核心词（服务端生成，供两段式查重第一段）
             * @example 鑫中网
             */
            name_core: string | null;
            /** @description 城市 */
            city?: string | null;
            /** @description 行业一级 */
            industry_l1?: string | null;
            /** @description 规模 */
            scale?: string | null;
            /** @description 统一社会信用代码（**列表给全量**；查重候选才用 `credit_code_masked`） */
            credit_code?: string | null;
            /**
             * @description 注册资本（单位＝元；前端按「万元」展示）
             * @example 5000000
             */
            registered_capital?: string | null;
            /** @description 法定代表人 */
            legal_person?: string | null;
            /** @description 地址是否维护（`address` 或坐标为空 → false）；派生展示，不落表 */
            address_maintained: boolean;
            /** @example 2026-09-15T10:00:00+08:00 */
            updated_at: string;
        };
        CreateCompanyDto: {
            /**
             * @description 公司全称（服务端据此生成 `name_core` 供查重）
             * @example 安徽鑫中网信息技术有限公司
             */
            full_name: string;
            /** @description 统一社会信用代码（可空；**撞码 → 409，请用已有档案**） */
            credit_code?: string;
            /** @description 行业一级 */
            industry_l1?: string;
            /** @description 行业二级 */
            industry_l2?: string;
            /** @description 省 */
            province?: string;
            /** @description 市 */
            city?: string;
            /** @description 区 / 县 */
            district?: string;
            /** @description 规模 */
            scale?: string;
            /** @description 官网 */
            website?: string;
            /** @description 注册地址（同时是签约校验清单「注册地址」项的落点） */
            address?: string;
            /** @description 开户行 */
            bank_name?: string;
            /** @description 发票抬头 */
            invoice_title?: string;
            /** @description 税号 */
            tax_no?: string;
            /**
             * @description **注册资本（单位＝元**；前端按「万元」录入并各做一次换算）。可选扩展字段，不参与签约强制与完善度
             * @example 5000000
             */
            registered_capital?: string;
            /** @description 法定代表人（可选扩展字段） */
            legal_person?: string;
            /**
             * @description 经度 GCJ-02
             * @example 117.227239
             */
            longitude?: string;
            /**
             * @description 纬度 GCJ-02
             * @example 31.820587
             */
            latitude?: string;
            /** @description 曾用名 / 别名（合并时自动收进） */
            aliases?: string[];
        };
        SearchDupDto: {
            /** @description 按**联系人手机号**查（撞库第 ① 个触发点，→ 需求 §12.1） */
            phone?: string;
            /** @description 按**统一社会信用代码**查（撞码 → 强制使用已有档案） */
            credit_code?: string;
            /** @description 按**公司名**查（两段式：`name_core` 收缩候选 → 编辑距离判级） */
            name?: string;
        };
        DupCandidateVoDto: {
            /** @example 1 */
            id: string;
            /** @description 公司全称（**给全**：销售要认出是不是这家） */
            full_name: string;
            /** @description 信用代码**打码**形态（→ §2.8；规格未给形态，暂为前 4 ＋ `****` ＋ 后 4） */
            credit_code_masked?: string | null;
            /**
             * @description 相似度 0~1（`same` 恒为 1）
             * @example 0.5
             */
            similarity: number;
            /**
             * @description 判级：`same`＝核心词完全相同；`high_sim`＝高度疑似
             * @enum {string}
             */
            match_type: "same" | "high_sim";
        };
        SearchDupResultVoDto: {
            /** @description 候选清单（可空数组） */
            candidates: components["schemas"]["DupCandidateVoDto"][];
            /**
             * @description 建议：**有候选一律 `use_exists`**（需求 §12.1 分支 4：疑似默认选现有），无候选才 `create_new`
             * @enum {string}
             */
            suggest: "use_exists" | "create_new";
        };
        ContactBriefVoDto: {
            /** @example 1 */
            id: string;
            /** @example 张伟 */
            name: string;
            /** @description 职位（来自 `company_contact.position`） */
            position?: string | null;
            /**
             * @description 打码手机号（列表 / 卡片出参形态，**不是权限**，→ §2.8）
             * @example 138****0000
             */
            phone_masked: string;
            /** @description 是否被 owner 上锁（M5 前恒为 false：锁的实现属 M5） */
            phone_locked: boolean;
            /**
             * @description 决策角色
             * @enum {string}
             */
            decision_role?: "decision" | "influence" | "execute";
            /** @description 是否当前在职（`company_contact.is_current`；历史就职给 false） */
            is_current: boolean;
        };
        ExtraPhoneDto: {
            /**
             * @description 类型
             * @example mobile
             * @enum {string}
             */
            type: "mobile" | "tel" | "wechat";
            /**
             * @description 号码
             * @example 13900000000
             */
            number: string;
            /** @description 备注 */
            note?: string;
        };
        CreateContactDto: {
            /**
             * @description 姓名
             * @example 张伟
             */
            name: string;
            /**
             * @description 主号（撞单校验核心；服务端会先做归一：去空格 / `+86` / `-`）
             * @example 13800000000
             */
            phone: string;
            /** @description 附加号（可多个；不参与撞单） */
            extra_phones?: components["schemas"]["ExtraPhoneDto"][];
            /** @description 微信 */
            wechat?: string;
            /** @description 邮箱 */
            email?: string;
            /** @description 性别 */
            gender?: string;
            /**
             * @description 生日 `YYYY-MM-DD`
             * @example 1985-06-01
             */
            birthday?: string;
            /**
             * @description 决策角色
             * @enum {string}
             */
            decision_role?: "decision" | "influence" | "execute";
            /** @description 个人自由标签 */
            tags?: string[];
            /** @description 就职公司 id（十进制字符串）；给了就同时写一条 `company_contact` */
            company_id?: string;
            /** @description 职位（配合 `company_id` 一起给） */
            position?: string;
        };
        ContactCreatedVoDto: {
            /** @example 1 */
            id: string;
            /** @example 张伟 */
            name: string;
            /**
             * @description 归一后的主号（**详情给全号**，与角色无关，→ §2.8）
             * @example 13800000000
             */
            phone: string;
            /** @description 命中历史号时的提示（**提示不拦截**，→ §5.5） */
            phone_history_hint?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    OrgController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description 统一响应包的 `data` 即本结构 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResultDto"];
                };
            };
        };
    };
    OrgController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description 统一响应包的 `data` 即本结构 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResultDto"];
                };
            };
        };
    };
    OrgController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 统一响应包的 `data` 即 `UserVO` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserVoDto"];
                };
            };
        };
    };
    OrgController_listDepartments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentVoDto"][];
                };
            };
        };
    };
    OrgController_listEmployees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeVoDto"][];
                };
            };
        };
    };
    OrgController_listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleVoDto"][];
                };
            };
        };
    };
    OrgController_listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionVoDto"][];
                };
            };
        };
    };
    CompanyController_listCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyVoDto"][];
                };
            };
        };
    };
    CompanyController_createCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyVoDto"];
                };
            };
        };
    };
    CompanyController_searchDup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchDupDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchDupResultVoDto"];
                };
            };
        };
    };
    CompanyController_listContacts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactBriefVoDto"][];
                };
            };
        };
    };
    CompanyController_createContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactCreatedVoDto"];
                };
            };
        };
    };
    CompanyController_listCompanyContacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 公司 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactBriefVoDto"][];
                };
            };
        };
    };
}
