/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 健康检查
         * @description 真查库一次（SELECT 1）后返回；数据库不可用时由异常过滤器统一收口为失败包
         */
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登录
         * @description `account`（**手机号 或 登录账号名，二选一、服务端判别**）＋ 密码 → 双令牌 ＋ 当前人信息。失败一律 401 / 20002 且**不区分**「账号不存在」与「密码错」
         */
        post: operations["OrgController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 刷新令牌
         * @description 用 `refresh_token` 换一对新令牌；**重新装载**最新角色与管辖部门（撤销经理后立即收窄数据范围）
         */
        post: operations["OrgController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 当前登录人
         * @description 返回角色 ＋ 管辖部门集合 ＋ 权限矩阵 ＋ 数据范围；`managed_dept_ids` 为空 = 非经理
         */
        get: operations["OrgController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 改个人偏好
         * @description 个人主题（`light` 白天 / `dark` 夜间，V1 两态）与侧栏展开状态，**存账号**（→ 设计规范 §八.1 / 需求 §13.4）。**部分更新**：不给的键一律原样保留；返回**更新后的 `UserVO`**（结构与 `GET /account/me` 完全相同）
         */
        put: operations["OrgController_updatePreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 部门列表
         * @description 树形关系由 `parent_id` 自带，前端自行组树（含经理与关联产品线）
         */
        get: operations["OrgController_listDepartments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/product-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 产品线列表
         * @description 含 `color_key`（7 条线固定配色，前端照渲染，→ 需求 §13.3）与承接部门集合。录入页激活业务关系时选产品线用（`POST /relations` req 含 `product_line_id`，→ §5.6）
         */
        get: operations["OrgController_listProductLines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/employees": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 员工列表
         * @description **不含密码哈希**；含主/兼部门、关联产品线、直属经理与角色码。**服务端按数据范围收敛**（管理员/总经理=全部；经理=管辖部门；销售=同部门，→ §4.2 G7）
         */
        get: operations["OrgController_listEmployees"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 角色列表
         * @description 内置 6 条（`is_builtin`，内置不可删）
         */
        get: operations["OrgController_listRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/org/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 权限矩阵
         * @description `perm_key × role_code → level` 全量矩阵行
         */
        get: operations["OrgController_listPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 公司档案列表
         * @description 按 id 倒序（**分页 / 筛选属 M6 列表页**，本批给最近 100 条）。⚠ 接口 §5.4 列表项里的 `relation_count` / `old_customer` 属 C / E 域，跨域不许查表 ⇒ 待 M3/M4 提供
         */
        get: operations["CompanyController_listCompanies"];
        put?: never;
        /**
         * 建档公司
         * @description 服务端生成 `name_core`（供两段式查重第一段）。`credit_code` 撞码 → **409「请使用已有档案」**；**疑似重复不拦建档**（需求 §12.1 分支 4：保留「强行新建」出口）
         */
        post: operations["CompanyController_createCompany"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/search-dup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 撞库查重
         * @description `phone` / `credit_code` 精确命中 → `same`；`name` 走两段式（`name_core` 前缀收缩 → 编辑距离判级 → `same` / `high_sim`）。**有候选即 `suggest=use_exists`**（疑似默认选现有），无候选才 `create_new`
         */
        post: operations["CompanyController_searchDup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 联系人列表
         * @description **列表出参一律 `phone_masked`**（→ §2.8，出参形态而非权限）。入参 `only_unlinked` ＝只看「**未关联公司**」的待跟进（→ 需求 §6.1 ③）。可见范围：「待关联」（未挂公司）**只给归属人自己**；已挂公司的人**暂按现状**（公司维度收敛待复用的数据范围判定，→《欠账登记表》D-28）
         */
        get: operations["CompanyController_listContacts"];
        put?: never;
        /**
         * 建档联系人
         * @description 主号先归一（去空格 / `+86` / `-`）再入库；**重复手机号 → 409**（软删后同号可再建）；命中历史号只提示 `phone_history_hint`、**不拦截**
         */
        post: operations["CompanyController_createContact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/companies/{id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 公司联系人
         * @description 含**历史就职 / 已离职标记**（`is_current`，→ B5）
         */
        get: operations["CompanyController_listCompanyContacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 业务关系列表
         * @description `tab=private`（默认）＝私海；`tab=sea`＝公海（＝无 owner 的关系）。**服务端按数据范围收敛**（→ §2.2）：销售＝我参与的关系 ＋ **我所属部门**的公海；经理＝管辖部门；总经理 / 管理员＝全部；**交付 / 客服看公海 → 403**（「不进公海」）。**M6-07 起分页**：`page`（默认 1）/ `page_size`（默认 20、最大 100），出参＝ §2.3 分页形态 `{list,total,page,page_size}`（**不再是裸数组**）；**筛选**：`view`（视图：`all` / `following` / `cooperated` / `churned`）＋ `urgency`（紧迫档**多选**、逗号分隔）—— `total` 数的是**筛完之后**的总数。排序恒 `id desc`（`order_by` / `keyword` 等属后续）。⚠ 规格 §5.6 列表项里 `drop_in_x_days` / `overdue` / `amount` / `old_customer` / `is_weekly` 属其它域（M4/M7/E），本批**不返回**（不填假值）
         */
        get: operations["RelationController_listRelations"];
        put?: never;
        /**
         * 激活业务关系
         * @description `{company_id, dept_id, product_line_id}` → 归属**发起人自己**（换人走 `transfer` 审批）。同 公司 × 部门 × 产品线 已有活跃关系 → **409 / 20401**（撞单）；`dept_id` 必须落在我可建范围内（销售＝我所属部门含兼职；经理＝管辖部门），否则 403
         */
        post: operations["RelationController_createRelation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 业务关系详情
         * @description 列表项 ＋ `members`（本批范围；`stage_logs` / `labels` / `competitors` / `rounds` 属后续里程碑）。**公海（无主）关系可读**（2026-09-18 定）：按**所属部门**开放 —— 销售＝本部门、经理＝管辖部门、总经理 / 管理员＝全部；**别部门 → 403**；**交付 / 客服不进公海**（→ §2.2）
         */
        get: operations["RelationController_getRelation"];
        /**
         * 改关系属性
         * @description `{urgency?, value_tier?, next_action_hint?, competition?, competitor_id?}`。⚠ **非灰度关系必标开发价值**：「已标」＝**有值且合法即可，`pending` 也算标过**（2026-09-15 拍板）；**完全没标**的非灰度关系 → **422 / 20403**（→ 数据架构 C1）。★ **公海（无主）关系的唯一写口**（2026-09-18 定）：**只传 `value_tier`** 时放行（开发价值＝**部门共同维护**，**销售也能标**；判定＝在本人读范围内 ＋ 可写角色，**不看 owner**）；**再带任何一个别的字段**（含空 body）→ **422 / `20408`**。⚠ 规格 §5.6 是 **`PUT`**（计划行写 PATCH，按铁律以规格为准）
         */
        put: operations["RelationController_updateRelation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relations/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 关系成员
         * @description 含**已撤销**的留痕行（→ C2）
         */
        get: operations["RelationController_listMembers"];
        put?: never;
        /**
         * 加关系成员
         * @description `{employee_id, member_type, source?, valid_until?}`。`owner` **一关系仅一人**（第二位 → 409）；`collaborator` 的 `source` 必填：`ask_help`（@求助）**限同部门**（跨部门 403，走正式协同审批），未给 `valid_until` 时默认 **7 天**。出参＝**加完之后的成员列表**。★ **公海（无主）关系 → 422 / `20408`**（未领取不加成员；2026-09-18 定）
         */
        post: operations["RelationController_addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relations/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 关系时间线（跟单事件）
         * @description **按事件时间倒序**；默认近 1 个月（`range=1m`），`range=all` 取全部。可见性**继承业务关系权限**（→ 需求 §10.2）：他人私海 **403**；**公海（无主）关系的跟单全文可读**（2026-09-18 定）：按**所属部门** —— 销售＝本部门、经理＝管辖部门、总经理 / 管理员＝全部，**别部门 403**、**交付 / 客服不进公海**（看不到历史就判断不出值不值得捞）。`branch` 的分界基准是**该关系的 owner**（不是当前登录人，→ 决策 #30）。⚠ 规格 §5.7 的 `pain_point` / `round_no` 本批**不返回**（卡点字典未接 / 轮次来源未落库）
         */
        get: operations["EngineController_listEvents"];
        put?: never;
        /**
         * 记一条跟单
         * @description `{contact_id?,action_type,summary?,outcome?,competition?,competition_note?,duration_min?,mentioned_user_ids?}`。**有效沟通必须写一句话结果**；快速标记三型（未联系 / 未接 / 说两句挂了）**点一下即可**（→ 需求 §10.2）。★ **写跟单只能在私海**：公海（无主）关系 → **422 / `20408`**（要写跟单请先领取到私海；2026-09-18 定）。重复提交（同内容）→ **409**；快速标记**不重置**掉海倒计时（→ 数据架构 D2）
         */
        post: operations["EngineController_recordEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/quick-mark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 批量快速标记（未联系 / 未接电话 / 说两句挂了）
         * @description `{relation_ids?:[],contact_ids?:[],outcome}`（**两组至少一组非空**）。**落库、可批量，但不算有效跟进、不更新 `last_event_at`**（→ 需求 §6.3 / §10.2：点一下不能保号）。重复点同一条**会落多条** ——「这个客户打过 N 次」正是这么统计的。⚠ 判定分两组：关系侧判**可写**（越权 / 只读 → 403）；「待关联」联系人侧判**归属人**（只有当前归属人能标，别人 → 403；→ 需求 §6.1 ⑦⑨）。★ 关系侧另加**非公海**：公海（无主）关系 → **422 / `20408`**（未领取不标记；2026-09-18 定）
         */
        post: operations["EngineController_quickMark"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/relations/{id}/commitments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 某关系的承诺列表
         * @description 可见性同时间线（**继承业务关系权限**，含**公海按所属部门可读**）；本批**不分页**（→ 接口 §2.7，M6）
         */
        get: operations["EngineController_listCommitments"];
        /**
         * 改承诺（兑现 / 取消 / 豁免 / 改期）
         * @description `{id,status?,waive_reason?,due_at?,remind_at?}`，`status` ∈ `done` 兑现 / `cancelled` 取消（**录错了 / 不成立**，不需原因）/ `waived` 豁免（**确有其事但做不成，必填 `waive_reason`**）。已结束的承诺（兑现 / 取消 / 豁免）再改 → **422 / 20403**；★ 公海（无主）关系 → **422 / `20408`**（2026-09-18 定）
         */
        put: operations["EngineController_updateCommitment"];
        /**
         * 建一条承诺
         * @description `{contact_id?,party,ctype,content,due_at?,remind_at?,source_event_id?}`。`party`：`me` 我答应客户（催自己）/ `them` 客户答应我（催客户）/ `verdict` 给结论（→ 需求 §10.1）；`due_at` 不给＝**未定**（「三快选默认明天」由前端给，服务端不替销售定时间）。★ 公海（无主）关系 → **422 / `20408`**（未领取不建承诺；2026-09-18 定）
         */
        post: operations["EngineController_createCommitment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/today-agenda": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 今日该找谁（工作台）
         * @description **只返回登录人自己的**动线条目（`daily_agenda.user_id`），且只含 `open` / `snoozed`（已办的 `done` / `ignored` 不再推）。⚠ 本批**不实时组装**：条目由每日 05:00 的组装任务产生（属 M7），库里没有当日行就是**空数组**。`relation` 可为 `null`（「只有联系人、还没挂关系」的提醒，→ 数据架构 D4）
         */
        get: operations["EngineController_todayAgenda"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            /**
             * @description 服务可用
             * @example true
             */
            ok: boolean;
            /**
             * @description 数据库连通状态（真跑了一次 SELECT 1）
             * @example up
             */
            db: string;
        };
        LoginDto: {
            /**
             * @description 登录标识：**手机号 或 登录账号名**（二选一，服务端判别）；前端只有一个输入框
             * @example 13800000003
             */
            account: string;
            /**
             * @description 密码明文（仅本次请求内存，不入库、不进日志）
             * @example Dev@123456
             */
            password: string;
        };
        EntityRefDto: {
            /**
             * @description 主键（十进制字符串，防 JSON 精度丢失）
             * @example 1
             */
            id: string;
            /**
             * @description 名称
             * @example 华东销售一部
             */
            name: string;
        };
        UserVoDto: {
            /** @example 7 */
            id: string;
            /** @example 张三 */
            name: string;
            /**
             * @description 登录账号名（**可空**：为空则只能手机号登录；→ §5.2）。服务端**始终下发该键**，无值给 `null`
             * @example zhangsan
             */
            username: string | null;
            /**
             * @description 主角色码（一人多角色时取权限最大者；内置码见 A4）
             * @example sale
             */
            role: string;
            /** @description 主部门；无部门数据时为 null */
            dept: components["schemas"]["EntityRefDto"] | null;
            /**
             * @description 管辖部门集合；**空数组 = 非经理**
             * @example [
             *       "1",
             *       "2"
             *     ]
             */
            managed_dept_ids: string[];
            /**
             * @description 权限矩阵（perm_key → level），level ∈ visible / masked / denied
             * @example {
             *       "customer.view": "visible"
             *     }
             */
            permissions: {
                [key: string]: string;
            };
            /**
             * @description 个人主题（V1 两态；→ 设计规范 §八.1 / 接口 §4.14.9）。**`null` = 从未设置过**（≠「显式选了白天」）—— 前端按「跟随默认值」回落
             * @example dark
             * @enum {string|null}
             */
            theme: "light" | "dark" | null;
            /**
             * @description 侧栏展开的分组键集合（→ 需求 §13.4「折叠状态按账号持久化」）。**始终下发该键**：没存过给 `[]`（≠ 用户手动全部收起，后者是用户在列表里收起后的结果）
             * @example [
             *       "relation"
             *     ]
             */
            nav_open: string[];
        };
        LoginResultDto: {
            /** @description 访问令牌（Bearer JWT，建议 2h） */
            access_token: string;
            /** @description 刷新令牌 */
            refresh_token: string;
            /** @description 当前登录人（前端据此渲染菜单 / 数据范围） */
            user: components["schemas"]["UserVoDto"];
        };
        RefreshDto: {
            /** @description 登录时下发的 `refresh_token`（JWT 串） */
            refresh_token: string;
        };
        RefreshResultDto: {
            /** @description 新的访问令牌 */
            access_token: string;
            /** @description 新的刷新令牌 */
            refresh_token: string;
        };
        UpdatePreferencesDto: {
            /**
             * @description 个人主题：`light` 白天 / `dark` 夜间（V1 两态）。**不传该键 = 不改**（部分更新）；清空设置本轮**不提供**（前端永远有一个明确的选中态）
             * @example dark
             * @enum {string}
             */
            theme?: "light" | "dark";
            /**
             * @description 侧栏展开的分组键集合（→ 需求 §13.4）。**不传该键 = 不改**（部分更新）；传空数组 = 用户手动全部收起（与「从未设置过」不同，后者库里是 `null`）
             * @example [
             *       "relation"
             *     ]
             */
            nav_open?: string[];
        };
        DepartmentVoDto: {
            /** @example 1 */
            id: string;
            /** @example 华东分公司 */
            name: string;
            /**
             * @description 上级部门 id；`0` = 根（自引用不建外键）
             * @example 0
             */
            parent_id: string;
            /**
             * @description 客服开关
             * @example false
             */
            service_enabled: boolean;
            /**
             * @description 状态（active / disabled）
             * @example active
             */
            status: string;
            /** @description 部门经理集合（→ A3 `dept_manager`，多对多） */
            manager_ids: string[];
            /** @description 关联产品线集合（由 A7 的 `dept_ids` 反向索引而来） */
            product_line_ids: string[];
        };
        ProductLineVoDto: {
            /** @example 5 */
            id: string;
            /** @example 标准建站线 */
            name: string;
            /**
             * @description 产品线英文码（→ A7 `code`）
             * @example STD
             */
            code: string;
            /**
             * @description 固定配色键（7 条线各一色，→ 需求 §13.3）；未配置为 `null`，前端自行回落
             * @example blue
             */
            color_key: string | null;
            /** @description 承接部门集合（A7 `dept_ids` 由 JSON 转十进制字符串） */
            dept_ids: string[];
            /**
             * @description 服务周期（天）；未配置为 `null`
             * @example 365
             */
            service_cycle_days: number | null;
            /**
             * @description 状态（active / disabled）
             * @example active
             */
            status: string;
        };
        EmployeeVoDto: {
            /** @example 7 */
            id: string;
            /**
             * @description 工号
             * @example A007
             */
            work_no: string;
            /** @example 张三 */
            name: string;
            /**
             * @description 手机号（主入口唯一键）
             * @example 13800000000
             */
            phone: string;
            /**
             * @description 登录账号名（可空：为空则只能手机号登录）
             * @example zhangsan
             */
            username: string | null;
            /** @description 主部门 */
            primary_dept: components["schemas"]["EntityRefDto"] | null;
            /** @description 兼部门 */
            extra_depts: components["schemas"]["EntityRefDto"][];
            /** @description 关联产品线 */
            product_lines: components["schemas"]["EntityRefDto"][];
            /** @description 直属经理（审批链） */
            direct_manager: components["schemas"]["EntityRefDto"] | null;
            /**
             * @description 角色码集合（→ A5）
             * @example [
             *       "sale"
             *     ]
             */
            roles: string[];
            /**
             * @description 状态（active / resigned / disabled）
             * @example active
             */
            status: string;
        };
        RoleVoDto: {
            /**
             * @description 角色码（内置 6 条）
             * @example sale
             */
            code: string;
            /** @example 销售 */
            name: string;
            /**
             * @description 是否内置（内置不可删）
             * @example true
             */
            is_builtin: boolean;
        };
        PermissionVoDto: {
            /**
             * @description 权限键
             * @example customer.view
             */
            perm_key: string;
            /**
             * @description 角色码
             * @example sale
             */
            role_code: string;
            /**
             * @description 档位（visible / masked / denied）
             * @example visible
             */
            level: string;
        };
        CompanyVoDto: {
            /** @example 1 */
            id: string;
            /** @example 安徽鑫中网信息技术有限公司 */
            full_name: string;
            /**
             * @description 标准化核心词（服务端生成，供两段式查重第一段）
             * @example 鑫中网
             */
            name_core: string | null;
            /** @description 城市 */
            city?: string | null;
            /** @description 行业一级 */
            industry_l1?: string | null;
            /** @description 规模 */
            scale?: string | null;
            /** @description 统一社会信用代码（**列表给全量**；查重候选才用 `credit_code_masked`） */
            credit_code?: string | null;
            /**
             * @description 注册资本（单位＝元；前端按「万元」展示）
             * @example 5000000
             */
            registered_capital?: string | null;
            /** @description 法定代表人 */
            legal_person?: string | null;
            /** @description 地址是否维护（`address` 或坐标为空 → false）；派生展示，不落表 */
            address_maintained: boolean;
            /** @example 2026-09-15T10:00:00+08:00 */
            updated_at: string;
        };
        CreateCompanyDto: {
            /**
             * @description 公司全称（服务端据此生成 `name_core` 供查重）
             * @example 安徽鑫中网信息技术有限公司
             */
            full_name: string;
            /** @description 统一社会信用代码（可空；**撞码 → 409，请用已有档案**） */
            credit_code?: string;
            /** @description 行业一级 */
            industry_l1?: string;
            /** @description 行业二级 */
            industry_l2?: string;
            /** @description 省 */
            province?: string;
            /** @description 市 */
            city?: string;
            /** @description 区 / 县 */
            district?: string;
            /** @description 规模 */
            scale?: string;
            /** @description 官网 */
            website?: string;
            /** @description 注册地址（同时是签约校验清单「注册地址」项的落点） */
            address?: string;
            /** @description 开户行 */
            bank_name?: string;
            /** @description 发票抬头 */
            invoice_title?: string;
            /** @description 税号 */
            tax_no?: string;
            /**
             * @description **注册资本（单位＝元**；前端按「万元」录入并各做一次换算）。可选扩展字段，不参与签约强制与完善度
             * @example 5000000
             */
            registered_capital?: string;
            /** @description 法定代表人（可选扩展字段） */
            legal_person?: string;
            /**
             * @description 经度 GCJ-02
             * @example 117.227239
             */
            longitude?: string;
            /**
             * @description 纬度 GCJ-02
             * @example 31.820587
             */
            latitude?: string;
            /** @description 曾用名 / 别名（合并时自动收进） */
            aliases?: string[];
        };
        SearchDupDto: {
            /** @description 按**联系人手机号**查（撞库第 ① 个触发点，→ 需求 §12.1） */
            phone?: string;
            /** @description 按**统一社会信用代码**查（撞码 → 强制使用已有档案） */
            credit_code?: string;
            /** @description 按**公司名**查（两段式：`name_core` 收缩候选 → 编辑距离判级） */
            name?: string;
        };
        DupCandidateVoDto: {
            /** @example 1 */
            id: string;
            /** @description 公司全称（**给全**：销售要认出是不是这家） */
            full_name: string;
            /** @description 信用代码**打码**形态（→ §2.8；规格未给形态，暂为前 4 ＋ `****` ＋ 后 4） */
            credit_code_masked?: string | null;
            /**
             * @description 相似度 0~1（`same` 恒为 1）
             * @example 0.5
             */
            similarity: number;
            /**
             * @description 判级：`same`＝核心词完全相同；`high_sim`＝高度疑似
             * @enum {string}
             */
            match_type: "same" | "high_sim";
        };
        SearchDupResultVoDto: {
            /** @description 候选清单（可空数组） */
            candidates: components["schemas"]["DupCandidateVoDto"][];
            /**
             * @description 建议：**有候选一律 `use_exists`**（需求 §12.1 分支 4：疑似默认选现有），无候选才 `create_new`
             * @enum {string}
             */
            suggest: "use_exists" | "create_new";
        };
        ContactBriefVoDto: {
            /** @example 1 */
            id: string;
            /** @example 张伟 */
            name: string;
            /** @description 职位（来自 `company_contact.position`） */
            position?: string | null;
            /**
             * @description 打码手机号（列表 / 卡片出参形态，**不是权限**，→ §2.8）
             * @example 138****0000
             */
            phone_masked: string;
            /** @description 手机号是否**对当前查看者**处于上锁态（＝锁开着、且查看者不是落锁人，→ 需求 §4.3 二）。⚠ 列表**本就一律 `phone_masked`**：本字段是「已上锁 ＋ 申请解锁」的提示，不是权限开关 */
            phone_locked: boolean;
            /**
             * @description 决策角色
             * @enum {string}
             */
            decision_role?: "decision" | "influence" | "execute";
            /** @description 是否当前在职（`company_contact.is_current`；历史就职给 false） */
            is_current: boolean;
        };
        ExtraPhoneDto: {
            /**
             * @description 类型
             * @example mobile
             * @enum {string}
             */
            type: "mobile" | "tel" | "wechat";
            /**
             * @description 号码
             * @example 13900000000
             */
            number: string;
            /** @description 备注 */
            note?: string;
        };
        CreateContactDto: {
            /**
             * @description 姓名
             * @example 张伟
             */
            name: string;
            /**
             * @description 主号（撞单校验核心；服务端会先做归一：去空格 / `+86` / `-`）
             * @example 13800000000
             */
            phone: string;
            /** @description 附加号（可多个；不参与撞单） */
            extra_phones?: components["schemas"]["ExtraPhoneDto"][];
            /** @description 微信 */
            wechat?: string;
            /** @description 邮箱 */
            email?: string;
            /** @description 性别 */
            gender?: string;
            /**
             * @description 生日 `YYYY-MM-DD`
             * @example 1985-06-01
             */
            birthday?: string;
            /**
             * @description 决策角色
             * @enum {string}
             */
            decision_role?: "decision" | "influence" | "execute";
            /** @description 个人自由标签 */
            tags?: string[];
            /** @description 就职公司 id（十进制字符串）；给了就同时写一条 `company_contact` */
            company_id?: string;
            /** @description 职位（配合 `company_id` 一起给） */
            position?: string;
        };
        ContactCreatedVoDto: {
            /** @example 1 */
            id: string;
            /** @example 张伟 */
            name: string;
            /**
             * @description 归一后的主号（**详情给全号**，与角色无关，→ §2.8）
             * @example 13800000000
             */
            phone: string;
            /** @description 命中历史号时的提示（**提示不拦截**，→ §5.5） */
            phone_history_hint?: string;
        };
        RelationRefDto: {
            /**
             * @description id（十进制字符串）
             * @example 3
             */
            id: string;
            /**
             * @description 名称快照（生成引用那一刻的库值）
             * @example 安徽鑫中网信息技术有限公司
             */
            name: string;
        };
        ProductLineRefDto: {
            /**
             * @description 产品线 id（十进制字符串）
             * @example 1
             */
            id: string;
            /**
             * @description 产品线名称
             * @example 网站建设
             */
            name: string;
            /**
             * @description 固定配色键（7 条线各一色，前端照渲染，→ 需求 §13.3）；**未配置给 `null`**
             * @example blue
             */
            color_key: string | null;
        };
        RelationVoDto: {
            /**
             * @description 业务关系 id
             * @example 1
             */
            id: string;
            /** @description 公司档案（档案被逻辑删时取不到引用 → `null`） */
            company: components["schemas"]["RelationRefDto"] | null;
            /** @description 承接部门（`dept_id` 恒定不可变，→ C1） */
            dept: components["schemas"]["RelationRefDto"] | null;
            /** @description 产品线（含固定配色键 `color_key`） */
            product_line: components["schemas"]["ProductLineRefDto"] | null;
            /**
             * @description 工作流阶段：1~6 ＋ 7＝已流失
             * @example 1
             */
            stage: number;
            /**
             * @description 紧迫档
             * @enum {string}
             */
            urgency: "weekly" | "monthly" | "quarterly" | "long_term" | "gray";
            /**
             * @description 开发价值档（非灰度关系**必标**，→ C1）
             * @enum {string|null}
             */
            value_tier: "high" | "medium" | "low" | "pending" | null;
            /** @description 客户等级（**系统按滚动 12 个月回款自动算、不手填** → E 域未接，本批恒 `null`） */
            customer_level: string | null;
            /** @description 主责销售（**公海关系为 `null`**） */
            owner: components["schemas"]["RelationRefDto"] | null;
            /**
             * @description `private`＝私海（有 owner）/ `company_sea`＝公海（无 owner）
             * @enum {string}
             */
            sea_status: "private" | "company_sea";
            /** @description 最近一次**有效沟通**时间（快速标记不计入，→ C1） */
            last_event_at: string | null;
            /** @description 一句话「上次说好下次干嘛」 */
            next_action_hint: string | null;
            /**
             * @description 竞品态势快照（`null`＝未知）
             * @enum {string|null}
             */
            competition: "none" | "in_use" | "comparing" | null;
            /** @description 建档时间（ISO） */
            created_at: string;
            /** @description 最近更新时间（ISO） */
            updated_at: string;
        };
        RelationPageVoDto: {
            /** @description 当前页数据 */
            list: components["schemas"]["RelationVoDto"][];
            /**
             * @description 符合筛选条件的全量条数（前端「共 N 条」）
             * @example 120
             */
            total: number;
            /**
             * @description 当前页码（从 1 开始）
             * @example 1
             */
            page: number;
            /**
             * @description 每页条数（默认 20，最大 100，→ §2.7）
             * @example 20
             */
            page_size: number;
        };
        CreateRelationDto: {
            /**
             * @description 公司档案 id（→ B1）
             * @example 3
             */
            company_id: string;
            /**
             * @description 承接部门 id —— **必须落在我可建范围内**（销售＝我所属部门含兼职；经理＝管辖部门；总经理＝任意）；⚠ `dept_id` 恒定不可变（→ 数据架构 C1），别部门想接＝自己激活一条
             * @example 2
             */
            dept_id: string;
            /**
             * @description 产品线 id（→ A7）
             * @example 1
             */
            product_line_id: string;
        };
        RelationMemberVoDto: {
            /** @description 成员员工（员工被停用时取不到引用 → `null`） */
            employee: components["schemas"]["RelationRefDto"] | null;
            /**
             * @description `owner`＝主责销售（一关系仅一人）/ `collaborator`＝协同人
             * @enum {string}
             */
            member_type: "owner" | "collaborator";
            /** @description `collaborate` 正式协同 / `ask_help` @求助；owner 为 `null` */
            source: string | null;
            /** @description 协同有效期（`null`＝长期，仅正式协同，→ C2） */
            valid_until: string | null;
        };
        RelationDetailVoDto: {
            /**
             * @description 业务关系 id
             * @example 1
             */
            id: string;
            /** @description 公司档案（档案被逻辑删时取不到引用 → `null`） */
            company: components["schemas"]["RelationRefDto"] | null;
            /** @description 承接部门（`dept_id` 恒定不可变，→ C1） */
            dept: components["schemas"]["RelationRefDto"] | null;
            /** @description 产品线（含固定配色键 `color_key`） */
            product_line: components["schemas"]["ProductLineRefDto"] | null;
            /**
             * @description 工作流阶段：1~6 ＋ 7＝已流失
             * @example 1
             */
            stage: number;
            /**
             * @description 紧迫档
             * @enum {string}
             */
            urgency: "weekly" | "monthly" | "quarterly" | "long_term" | "gray";
            /**
             * @description 开发价值档（非灰度关系**必标**，→ C1）
             * @enum {string|null}
             */
            value_tier: "high" | "medium" | "low" | "pending" | null;
            /** @description 客户等级（**系统按滚动 12 个月回款自动算、不手填** → E 域未接，本批恒 `null`） */
            customer_level: string | null;
            /** @description 主责销售（**公海关系为 `null`**） */
            owner: components["schemas"]["RelationRefDto"] | null;
            /**
             * @description `private`＝私海（有 owner）/ `company_sea`＝公海（无 owner）
             * @enum {string}
             */
            sea_status: "private" | "company_sea";
            /** @description 最近一次**有效沟通**时间（快速标记不计入，→ C1） */
            last_event_at: string | null;
            /** @description 一句话「上次说好下次干嘛」 */
            next_action_hint: string | null;
            /**
             * @description 竞品态势快照（`null`＝未知）
             * @enum {string|null}
             */
            competition: "none" | "in_use" | "comparing" | null;
            /** @description 建档时间（ISO） */
            created_at: string;
            /** @description 最近更新时间（ISO） */
            updated_at: string;
            /** @description 成员（含已撤销的留痕行，按加入先后） */
            members: components["schemas"]["RelationMemberVoDto"][];
        };
        UpdateRelationDto: {
            /**
             * @description 紧迫档（纯手动，无自动降级）
             * @enum {string}
             */
            urgency?: "weekly" | "monthly" | "quarterly" | "long_term" | "gray";
            /**
             * @description 开发价值档。⚠ 非灰度关系**必标** ——「已标」＝**有值且合法即可，`pending` 也算标过**（2026-09-15 拍板），**完全没标**才 **422 / 20403**
             * @enum {string}
             */
            value_tier?: "high" | "medium" | "low" | "pending";
            /**
             * @description 一句话「上次说好下次干嘛」
             * @example 周四带样机再谈
             */
            next_action_hint?: string;
            /**
             * @description 竞品态势快照（录入在事件侧，此处为修正）
             * @enum {string}
             */
            competition?: "none" | "in_use" | "comparing";
            /**
             * @description 竞品名册 id（→ C7）
             * @example 1
             */
            competitor_id?: string;
        };
        AddRelationMemberDto: {
            /**
             * @description 员工 id
             * @example 3
             */
            employee_id: string;
            /**
             * @description `owner` 一关系仅一人（已有归属 → 409）；`collaborator` 可多人
             * @enum {string}
             */
            member_type: "owner" | "collaborator";
            /**
             * @description 仅协同人需要：`collaborate`＝正式协同（审批通过）／`ask_help`＝@求助（**限同部门**，未给 `valid_until` 时默认 7 天）
             * @enum {string}
             */
            source?: "collaborate" | "ask_help";
            /** @description 协同有效期（ISO 日期；`null` / 缺省＝长期，仅正式协同） */
            valid_until?: string;
        };
        EngineRefDto: {
            /**
             * @description id（十进制字符串）
             * @example 7
             */
            id: string;
            /**
             * @description 名称快照（取引用那一刻的库值）
             * @example 王海涛
             */
            name: string;
        };
        ActionEventVoDto: {
            /**
             * @description 事件 id
             * @example 1
             */
            id: string;
            /**
             * @description 动作类型（→ D2）
             * @example phone
             */
            action_type: string;
            /** @description 一句话结果（**快速标记时为 `null`**） */
            summary: string | null;
            /**
             * @description 结果码（空＝中性，→ D2）
             * @example advanced
             */
            outcome: string | null;
            /**
             * @description 本次了解的竞品态势（→ C1 快照）
             * @example none
             */
            competition: string | null;
            /** @description 谁填的（操作人） */
            actor: components["schemas"]["EngineRefDto"];
            /** @description **本条创建时该关系的归属人**（→ D2 `owner_snapshot`：按轮次归组 ＋ 前主人标姓名用）。关系暂无 owner（如已掉公海）时为 `null` */
            owner_snapshot: components["schemas"]["EngineRefDto"] | null;
            /** @description 本次跟进的联系人（**选填**，→ 需求 §6.3 多联系人口径） */
            contact: components["schemas"]["EngineRefDto"] | null;
            /** @description 本次投入分钟 */
            duration_min: number | null;
            /** @description 事件发生时间（时间线排序基准，→ D2 `event_at`） */
            event_at: string;
            /**
             * @description `main`＝本条是**该关系 owner** 写的（主线）；`sub`＝协同 / 他人写的（树杈）—— **分界基准是 owner，不是当前登录人**（→ 决策 #30：经理打开时看到的也是主跟单人视角）
             * @enum {string}
             */
            branch: "main" | "sub";
            /** @description 附件（本批不接收，恒为 `[]`） */
            attachments: {
                [key: string]: unknown;
            }[];
        };
        CreateEventDto: {
            /**
             * @description 本次对着哪个联系人（**选填**，→ 需求 §6.3 多联系人：见谁都算有效跟进，不按角色加权）
             * @example 5
             */
            contact_id?: string;
            /**
             * @description 动作类型（→ D2）。`meal` / `gift` / `greeting`＝客情；`ask_help`＝@求助；`note`＝纯备注；`system`＝系统事件
             * @example phone
             * @enum {string}
             */
            action_type: "phone" | "wechat" | "visit" | "onsite" | "email" | "meal" | "gift" | "greeting" | "ask_help" | "note" | "system";
            /**
             * @description 一句话结果（≤200 字）。**有效沟通必填，快速标记可空** —— `outcome` ∈ 未联系 / 未接电话 / 说两句挂了 时不强制写一个字（→ 需求 §10.2）
             * @example 客户说下周一再谈，等他们内部过会
             */
            summary?: string;
            /**
             * @description 结果。**有效沟通**：advanced（有进展）/ stalled（卡住）/ await_reply（等回复）；**快速标记（无效沟通，不重置掉海倒计时）**：not_contacted / no_answer / brief_hangup。空＝中性（非必填，且**算有效沟通**）
             * @enum {string}
             */
            outcome?: "advanced" | "stalled" | "await_reply" | "not_contacted" | "no_answer" | "brief_hangup";
            /**
             * @description 本次跟单了解的竞品态势（→ D2：事务回写 C1 快照）
             * @enum {string}
             */
            competition?: "none" | "in_use" | "comparing";
            /** @description 竞品情况一句话（≤100 字） */
            competition_note?: string;
            /**
             * @description 本次投入分钟（算单位时间价值）
             * @example 30
             */
            duration_min?: number;
            /**
             * @description @求助的同事 id 列表（十进制字符串）。**仅正向展示**（卡片上"本条 @了谁"）；授权另走 `relation_member.ask_help`（→ D2 / C2），本列**不做反向查询**
             * @example [
             *       "8"
             *     ]
             */
            mentioned_user_ids?: string[];
        };
        QuickMarkDto: {
            /**
             * @description 要标记的业务关系 id 列表（十进制字符串）。与 `contact_ids` 至少一组非空
             * @example [
             *       "5",
             *       "4"
             *     ]
             */
            relation_ids?: string[];
            /**
             * @description 「待关联」（未挂公司）联系人的 id 列表（十进制字符串）。**只有该联系人的当前归属人才能标记**（别人 → **403**）—— 归属＝建档人、可改（→ 需求 §6.1 ⑦⑨）
             * @example [
             *       "7"
             *     ]
             */
            contact_ids?: string[];
            /**
             * @description 快速标记三型：`not_contacted` 未联系 / `no_answer` 未接电话 / `brief_hangup` 说两句挂了（→ 需求 §10.2）。**不算有效跟进、不重置掉海倒计时**（→ 需求 §6.3）
             * @example no_answer
             * @enum {string}
             */
            outcome: "not_contacted" | "no_answer" | "brief_hangup";
        };
        QuickMarkResultDto: {
            /**
             * @description 实际落库的事件条数（＝去重后能写的关系数）
             * @example 3
             */
            marked: number;
        };
        CommitmentVoDto: {
            /**
             * @description 承诺 id
             * @example 9
             */
            id: string;
            /**
             * @description 所属业务关系 id
             * @example 11
             */
            relation_id: string;
            /**
             * @description 承诺三型：`me` 我答应客户 / `them` 客户答应我 / `verdict` 我定的判定点
             * @example me
             * @enum {string}
             */
            party: "me" | "them" | "verdict";
            /**
             * @description 承诺类型（→ 数据架构 D1）
             * @example deliver
             */
            ctype: string;
            /**
             * @description 一句话承诺内容
             * @example 周三前把报价单发过去
             */
            content: string;
            /** @description 到期时间（未定＝`null`） */
            due_at: string | null;
            /** @description 提醒时间（未定＝`null`） */
            remind_at: string | null;
            /**
             * @description 状态。`open` 进行中 / `done` 已兑现 / `expired` 已逾期（派生态，按 `due_at` 算）/ `waived` 已豁免（**必填原因**，理由见 `waive_reason`）/ `cancelled` 已取消
             * @example open
             * @enum {string}
             */
            status: "open" | "done" | "expired" | "waived" | "cancelled";
            /** @description 豁免原因（**仅 `status=waived` 有值**，其余状态为 `null`）。`cancelled` 与 `waived` 的分界：取消＝**录错了 / 不成立**（不填原因）；豁免＝**确有其事但做不成**（客户变卦 / 特殊原因…，**必填**）（→ 需求 §10.1） */
            waive_reason: string | null;
            /** @description 兑现时间（未兑现＝`null`） */
            done_at: string | null;
        };
        CreateCommitmentDto: {
            /**
             * @description 对着哪个联系人（**选填**，同事件口径：不选也可提交）
             * @example 5
             */
            contact_id?: string;
            /**
             * @description 承诺三型：`me` 我答应客户（**催自己**）/ `them` 客户答应我（**催客户**）/ `verdict` 我定的判定点（**给个结论**）—— → 需求 §10.1
             * @example me
             * @enum {string}
             */
            party: "me" | "them" | "verdict";
            /**
             * @description 承诺类型（→ 数据架构 D1：9 种，`social_*` 为客情类）
             * @example deliver
             * @enum {string}
             */
            ctype: "reply" | "quote" | "meet" | "deliver" | "decision" | "followup" | "social_meal" | "social_gift" | "social_greeting";
            /**
             * @description 一句话承诺内容（≤255 字）
             * @example 周三前把报价单发过去
             */
            content: string;
            /**
             * @description 到期时间（ISO 字符串）。**前端「三快选」默认明天**，服务端**不替销售定时间**（不给＝未定，→ 需求 §10.1）
             * @example 2026-09-16T00:00:00.000Z
             */
            due_at?: string;
            /**
             * @description 提醒时间（ISO 字符串）；不给＝到期当天清晨（组装时算，属 M7）
             * @example 2026-09-16T01:00:00.000Z
             */
            remind_at?: string;
            /**
             * @description 由哪条跟单产生（选填；写事件的「有承诺吗」三快选带过来，→ 需求 §10.1）
             * @example 101
             */
            source_event_id?: string;
        };
        UpdateCommitmentDto: {
            /**
             * @description 要改哪条承诺（十进制字符串）
             * @example 9
             */
            id: string;
            /**
             * @description 流转到（→ 需求 §10.1 收尾三态）：`done` 兑现（写 `done_at` / `done_by`）/ `cancelled` 取消（**录错了 / 不成立**，不需原因）/ `waived` 豁免（**必填原因**，见 `waive_reason`）。已结束的承诺（兑现 / 取消 / 豁免）再改 → **422 / 20403**
             * @example done
             * @enum {string}
             */
            status?: "done" | "cancelled" | "waived";
            /**
             * @description 豁免原因（**仅 `status=waived` 时传，且必填** ≤255 字；兑现 / 取消 / 改期一律不传）。★ 为什么豁免必填而取消不必填：取消＝记录本身错了（纠错），豁免＝记录没错、但结果没成 ——不写原因，经理事后分不清"这条线还有没有戏"（→ 需求 §10.1）
             * @example 客户内部预算冻结，本季度不启动
             */
            waive_reason?: string;
            /**
             * @description 改期（ISO 字符串）
             * @example 2026-09-20T00:00:00.000Z
             */
            due_at?: string;
            /**
             * @description 改提醒时间（ISO 字符串）
             * @example 2026-09-20T01:00:00.000Z
             */
            remind_at?: string;
        };
        AgendaItemVoDto: {
            /**
             * @description 动线条目 id
             * @example 31
             */
            id: string;
            /**
             * @description 这条因何而来：承诺 / 预约 / 节奏规则命中 / 关系（掉海硬提醒）
             * @example commitment
             * @enum {string}
             */
            ref_type: "commitment" | "appointment" | "cadence" | "relation";
            /** @description 来源对象 id（如承诺 id） */
            ref_id: string | null;
            /** @description 哪条业务关系（`name` 取公司全称，→ C 域出口）。**可为 `null`**：动线条目存在「只有联系人、还没挂关系」的形态（→ 数据架构 D4 `relation_id` 可空） */
            relation: components["schemas"]["EngineRefDto"] | null;
            /** @description 对着哪个联系人（可为 `null`） */
            contact: components["schemas"]["EngineRefDto"] | null;
            /** @description 为什么今天该找 TA */
            reason: string | null;
            /**
             * @description 优先级（越大越靠前）
             * @example 10
             */
            priority: number;
            /** @description 建议动作（人话） */
            action_hint: string | null;
            /**
             * @description 处理状态（列表只返回 `open` / `snoozed`，见仓储注释）
             * @example open
             * @enum {string}
             */
            status: "open" | "done" | "snoozed" | "ignored";
            /**
             * @description 已被「明天再说」几次（上限 3，→ 需求 §10.4）
             * @example 0
             */
            snooze_count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    OrgController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            /** @description 统一响应包的 `data` 即本结构 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResultDto"];
                };
            };
        };
    };
    OrgController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            /** @description 统一响应包的 `data` 即本结构 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResultDto"];
                };
            };
        };
    };
    OrgController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 统一响应包的 `data` 即 `UserVO` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserVoDto"];
                };
            };
        };
    };
    OrgController_updatePreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesDto"];
            };
        };
        responses: {
            /** @description 统一响应包的 `data` 即更新后的 `UserVO` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserVoDto"];
                };
            };
        };
    };
    OrgController_listDepartments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DepartmentVoDto"][];
                };
            };
        };
    };
    OrgController_listProductLines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductLineVoDto"][];
                };
            };
        };
    };
    OrgController_listEmployees: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmployeeVoDto"][];
                };
            };
        };
    };
    OrgController_listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleVoDto"][];
                };
            };
        };
    };
    OrgController_listPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionVoDto"][];
                };
            };
        };
    };
    CompanyController_listCompanies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyVoDto"][];
                };
            };
        };
    };
    CompanyController_createCompany: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCompanyDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompanyVoDto"];
                };
            };
        };
    };
    CompanyController_searchDup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchDupDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchDupResultVoDto"];
                };
            };
        };
    };
    CompanyController_listContacts: {
        parameters: {
            query?: {
                /** @description 只看「**未关联公司**」的待跟进联系人（＝「待关联」视图，→ 需求 §6.1 ③：判定＝该联系人**无任何 `company_contact` 记录**） */
                only_unlinked?: "true" | "false";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactBriefVoDto"][];
                };
            };
        };
    };
    CompanyController_createContact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateContactDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactCreatedVoDto"];
                };
            };
        };
    };
    CompanyController_listCompanyContacts: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 公司 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContactBriefVoDto"][];
                };
            };
        };
    };
    RelationController_listRelations: {
        parameters: {
            query?: {
                /** @description `private`＝私海（我参与 / 管辖部门 / 全部）；`sea`＝公海（＝无 owner 的关系） */
                tab?: "private" | "sea";
                /** @description 页码（默认 1；`< 1` 回第 1 页） */
                page?: number;
                /** @description 每页条数（默认 20；超 100 按 100 计） */
                page_size?: number;
                /** @description 视图（→ 前端文档 §5）：`all`＝我的全部（不过滤）/ `following`＝跟进中（阶段 1~5）/`cooperated`＝已合作（阶段 6）/ `churned`＝已流失（阶段 7）。⚠ 前端 §5 另有一档「逾期未跟进」，**本批不提供** —— 它要判「逾期」，而逾期唯一来源是承诺 / 预约（D 域），字段尚未落地（→《欠账登记表》D-10）；**不编一个假的逾期定义** */
                view?: "all" | "following" | "cooperated" | "churned";
                /** @description 紧迫档**多选**，逗号分隔（→ 需求 §8.2 五档）：`weekly` 周重点 / `monthly` 月重点 / `quarterly` 季度跟 / `long_term` 长期跟 / `gray` 灰度；不传＝不筛。空串按「没筛」处理 */
                urgency?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationPageVoDto"];
                };
            };
        };
    };
    RelationController_createRelation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRelationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationVoDto"];
                };
            };
        };
    };
    RelationController_getRelation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 关系 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationDetailVoDto"];
                };
            };
        };
    };
    RelationController_updateRelation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 关系 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRelationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationVoDto"];
                };
            };
        };
    };
    RelationController_listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 关系 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationMemberVoDto"][];
                };
            };
        };
    };
    RelationController_addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 关系 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddRelationMemberDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RelationMemberVoDto"][];
                };
            };
        };
    };
    EngineController_listEvents: {
        parameters: {
            query?: {
                /** @description 时间窗：`1m` ＝近 1 个月（默认，→ §5.7）；`all` ＝全部 */
                range?: "1m" | "all";
            };
            header?: never;
            path: {
                /** @description 关系 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionEventVoDto"][];
                };
            };
        };
    };
    EngineController_recordEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 关系 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionEventVoDto"];
                };
            };
        };
    };
    EngineController_quickMark: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuickMarkDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuickMarkResultDto"];
                };
            };
        };
    };
    EngineController_listCommitments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 关系 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitmentVoDto"][];
                };
            };
        };
    };
    EngineController_updateCommitment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 关系 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommitmentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitmentVoDto"];
                };
            };
        };
    };
    EngineController_createCommitment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 关系 id（十进制字符串） */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommitmentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommitmentVoDto"];
                };
            };
        };
    };
    EngineController_todayAgenda: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgendaItemVoDto"][];
                };
            };
        };
    };
}
